name: PR - GitHub Enterprise Terraform
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions: # This is the permissions level for the workflow
  id-token: write
  contents: read
  repository-projects: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }} #${{ secrets.GITHUB_TOKEN }}
      ARM_USE_OIDC: true # This is required for GitHub Actions to authenticate in Azure using Microsoft's Entra ID application(ARM_CLIENT_ID).
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: Azure/login@v2.2.0
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false 
