name: GitHub Enterprise Terraform
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'github-enterprises-deploy'
    permissions: write-all      # This is the permissions level for the job
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ARM_USE_OIDC: true # This is required for GitHub Actions to authenticate in Azure using Microsoft's Entra ID application(ARM_CLIENT_ID).
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: Azure/login@v2.2.0        
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          environment: AzureCloud

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false 

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.ORGMGM_REPOS_01_APPID }}
          private-key: ${{ secrets.ORGMGM_REPOS_01_PKEY }}
       
      - name: Terraform Apply
        if: ${{ github.ref == 'refs/heads/main' }}
        run: terraform apply -auto-approve -input=false
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
